### ISSUE TITLE
Why can't I add new dataset?

### ISSUE THREAD

**Issue by Celestto** [mhaut/ROhsi#1]
I wanted to use other hyperspectral dataset, such as Kennedy Space Center (KSC), but when I added the information of KSC into auxil.py, 'KeyError' always happened. 
I don't know the reason and how to debug, can you help me?

**Comment by mhaut** [comment]
Dear Celestto,

Sure, but I do not know what problem you have if I do not see your code. I think your mistake is because the key you use in scipy.io.loadmat does not exist in the mat file. I have added in this code KSC dataset.

Best Regards.
